### ISSUE TITLE
use return instead of clearreturn on OsX/webdriver

### ISSUE THREAD

**Issue by fwoeck** [markgandolfo/send-keys#1]
Hi Mark,

thank you for your plugin! 
"clearreturn" throws an error with OsX10.64/webdriver, but using "return" instead works.

btw. do you see any option to make this work for culerity? When I write
  class Capybara::Driver::Celerity < Capybara::Driver::Base
I get this error:

NoMethodError: undefined method `send_keys' for #Celerity::TextField:0x2fb24628 (Culerity::CulerityException)

which probably means, that celerities api is different, right?

-- Frank

**Comment by markgandolfo** [comment]
Hi Frank, 

At I've fixed the documentation, thanks for bringing this to my attention. 

As for culerity support, I'll have to look at how culerity sends input to the browser. From an initial peek it doesn't seem to support it in the ruby gem, so a bit more time will need to be spent. 

Thanks 
Mark

**Comment by fwoeck** [comment]
Mark,

did you consider also 
chaging send-keys / support / send_keys.rb
line #5 ? ;)

-- Frank

**Comment by markgandolfo** [comment]
sorry frank, this got lost in my inbox.. I've pushed the fixes.
