### ISSUE TITLE
Key* events not triggered

### ISSUE THREAD

**Issue by ghost** [markgandolfo/send-keys#4]
Hi Mark, great work with this plugin! 

We've been trying this out (we used the following change to get things running with Capybara 0.4.0 : http://qastuffs.blogspot.com/2010/11/how-to-send-keystrokes-to-element-in.html) with a fairly complex interface which depends on watching keyup events with JQuery. While an input field is content can be sent it seems the keyup event is not triggered and our test fails. Are we missing a trick here or have you any experience with that?

**Comment by markgandolfo** [comment]
Not all keys work on all OS', have you tried on a mac/unix env to see if there are different responses?
