### ISSUE TITLE
Capybara 0.4 compatibility

### ISSUE THREAD

**Issue by simaob** [markgandolfo/send-keys#5]
Hi Mark,

you have a really nice add-on here. But I was using it with Capybara 0.4.0 and got this warning:

Capybara #node is deprecated, please use #native instead

For what I've seen the change is rather simple, so don't even think a patch is necessary:
=> old
node.send_keys(send_key)
=> new
native.send_keys(send_key)

this removes the warning, as far as I can tell. =)

Tks for the add-on! =)

**Comment by markgandolfo** [comment]
Thanks, I want to make sure that the plugin is still backwards compatible, I'll have a play around with it in the next few days..

**Comment by simaob** [comment]
yes that makes sense. =)

cheers!
