### ISSUE TITLE
DEPRECATED: #node is deprecated, please use #native instead

### ISSUE THREAD

**Issue by mariozaizar** [markgandolfo/send-keys#6]
I got this warning, DEPRECATED: #node is deprecated, please use #native instead
I've tried changing the native call, in the support file.. but I don't feel that is enough.

**Comment by bhavinjavia** [comment]
+1

**Comment by bhavinjavia** [comment]
While we wait for the fix, we've forked and fix it here -> https://github.com/Ennova/send-keys/commit/0abe06c1d1ac8d603a94a6ee28b5977ba0401629
